name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_pretty_dio_logger: ^3.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.13
  go_router: ^14.4.1
  iconsax_plus: ^1.0.0
  lottie: ^3.1.3
  otp: ^3.1.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/lotties/
    - lib/assets/svgs/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: lib/assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 600
        - asset: lib/assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 700
        - asset: lib/assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 800
        - asset: lib/assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900
        - asset: lib/assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 900
          style: italic
